---
platform: linux
image: docker:///boshcpi/azure-cpi-release
inputs:
  - name: bosh-softlayer-tools
  - name: baremetal-server-release
run:
  path: baremetal-server-release/ci/tasks/cleanup.sh
params:
  BOSH_INIT_LOG_LEVEL:        warn