---
platform: linux
image: docker:///boshcpi/azure-cpi-release
inputs:
  - name: stemcell
  - name: baremetal-server-release
  - name: baremetal-server-dev-artifacts
outputs:
  - name: deployment
run:
  path: baremetal-server-release/ci/tasks/setup-director.sh
params:
  BM_STEMCELL:                replace-me
  NETBOOT_IMAGE:              replace-me
  SL_USERNAME:                replace-me
  SL_API_KEY:                 replace-me
  SL_DATACENTER:              replace-me
  SL_VLAN_PUBLIC:             replace-me
  SL_VLAN_PRIVATE:            replace-me
  SL_VM_NAME_PREFIX:          replace-me
  SL_VM_DOMAIN:               softlayer.com
  BOSH_INIT_LOG_LEVEL:        warn