---
platform: linux
image: docker:///boshcpi/azure-cpi-release
inputs:
  - name: stemcell
  - name: baremetal-server-release
  - name: baremetal-server-dev-artifacts
  - name: dummy-release
outputs:
  - name: dummy-deployment
run:
  path: baremetal-server-release/ci/tasks/deploy-dummy-release.sh
params:
  BM_STEMCELL:                bosh-stemcell-0.3-softlayer-baremetal
  BM_NETBOOT_IMAGE:           bps-netboot-ixgbe-lon02
  SL_USERNAME:                replace-me
  SL_API_KEY:                 replace-me
  SL_DATACENTER:              replace-me
  SL_VLAN_PUBLIC:             replace-me
  SL_VLAN_PRIVATE:            replace-me
  SL_BM_NAME_PREFIX:          replace-me
  SL_BM_DOMAIN:               bluemix.com
  BOSH_INIT_LOG_LEVEL:        warn