---
platform: linux
image: docker:///boshcpi/azure-cpi-release
inputs:
  - name: stemcell
  - name: baremetal-server-release
  - name: baremetal-server-dev-artifacts
outputs:
  - name: bps-deployment
run:
  path: baremetal-server-release/ci/tasks/deploy-baremetal-server.sh
params:
  BM_STEMCELL:                bosh-stemcell-3232.11-softlayer
  NETBOOT_IMAGE:              bps-netboot-ixgbe-lon02
  SL_USERNAME:                replace-me
  SL_API_KEY:                 replace-me
  SL_DATACENTER:              replace-me
  SL_VLAN_PUBLIC:             replace-me
  SL_VLAN_PRIVATE:            replace-me
  SL_BM_NAME_PREFIX:          replace-me
  SL_BM_DOMAIN:               bluemix.com
  BOSH_INIT_LOG_LEVEL:        warn