---
platform: linux
image: docker:///boshcpi/azure-cpi-release
inputs:
  - name: bosh-baremetal-server-dev-artifacts
  - name: version-semver
  - name: bosh-baremetal-server-release
  - name: bosh-init
  - name: bosh-release
  - name: stemcell
outputs:
  - name: deployment
run:
  path: bosh-baremetal-server-release/ci/tasks/setup-director.sh
params:
  BASE_OS:                    replace-me
  SL_USERNAME:                replace-me
  SL_API_KEY:                 replace-me
  SL_DATACENTER:              replace-me
  SL_VLAN_PUBLIC:             replace-me
  SL_VLAN_PRIVATE:            replace-me
  SL_VM_NAME_PREFIX:          replace-me
  SL_VM_DOMAIN:               softlayer.com
  BOSH_INIT_LOG_LEVEL:        warn