---
platform: linux
image: docker:///boshcpi/azure-cpi-release
inputs:
  - name: bosh-softlayer-tools
  - name: baremetal-server-release
run:
  path: baremetal-server-release/ci/tasks/verify-baremetal-server.sh
params:
  SL_DATACENTER:              replace-me
  SL_VLAN_PUBLIC:             replace-me
  SL_VLAN_PRIVATE:            replace-me
  SL_VM_NAME_PREFIX:          replace-me
  SL_VM_DOMAIN:               softlayer.com
  BM_STEMCELL:                bosh-stemcell-0.3-softlayer-baremetal
  BM_NETBOOT_IMAGE:           bps-netboot-ixgbe