---
dev_name: baremetal-provision-server
latest_release_filename: "/Users/zhanggong/zhgworkspace/uploadToRepo/bosh-softlayer-baremetal-server-release/dev_releases/baremetal-provision-server/baremetal-provision-server-0+dev.2.yml"
