---
name: vps

releases:
- name: postgres
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=8
  sha1: 2fa36c58f53318ad3eb2d2c43908ed5275584b6e
- name: vps
  url: https://s3.amazonaws.com/bosh-softlayer-pooling/bosh-softlayer-pool-server-1.tgz
  sha1: 487BAFD708111323FA4DB1E7F3CC3A05BB096157
- name: bosh-softlayer-cpi
  url: https://s3.amazonaws.com/bosh-softlayer-cpi-pipeline/bosh-softlayer-cpi-0.0.307.tgz
  sha1: ef17ded2975c40fc08cffdeddf46901a1c49753c

resource_pools:
- name: vms
  network: default
  stemcell:
    url: https://s3.amazonaws.com/bosh-softlayer-stemcells-bluemix/light-bosh-stemcell-3263.10.3-softlayer-xen-ubuntu-trusty-go_agent.tgz
    sha1: e79079ca9a1aca910fb346d8ae0d02fcc8b688cd
  cloud_properties:
    Domain: softlayer.com
    VmNamePrefix: vps-server
    EphemeralDiskSize: 100
    StartCpus: 4
    MaxMemory: 8192
    Datacenter:
       Name: <datacenter_name>
    HourlyBillingFlag: true
    LocalDiskFlag: true
    PrimaryNetworkComponent:
       NetworkVlan:
          Id: <public_vlan_id>
    PrimaryBackendNetworkComponent:
       NetworkVlan:
          Id: <private_vlan_id>
    NetworkComponents:
    - MaxSpeed: 1000
disk_pools:
- name: disks
  disk_size: 40_000


networks:
- name: default
  type: dynamic
  dns:
  - 8.8.8.8

jobs:
- name: vps
  instances: 1

  templates:
  - {name: postgres, release: postgres}
  - {name: vps, release: bosh-softlayer-pool-server}

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - name: default

  properties:
    databases:
      roles:
      - name: postgres
      password: postgres
      address: 127.0.0.1
      port: 5432
      databases:
      - name: bosh
    vps:
      host: 0.0.0.0
      port: 8889
      log_level: debug
      sql:
        db_username: postgres
        db_password: postgres
        db_host: 127.0.0.1
        db_port: 5432
        db_schema: bosh
        db_driver: postgres
      tls:
        required: true         <Please set to 'true' if you need to enable https>
        host: 0.0.0.0          <Host at which to serve secure API requests>
        port: 443              <Port at which to serve secure API requests>
        server_pem:            <Please provide server certificate >
        server_key:            <Please provide server key>

    softlayer: &softlayer
      username: <username>   <Please replace it with your username>
      apiKey: <apikey>   <Please replace it with your apikey>

    agent: {mbus: "nats://nats:nats@127.0.0.1:4222"}

    ntp: &ntp []

cloud_provider:
  template: {name: softlayer_cpi, release: bosh-softlayer-cpi}

  # Tells bosh-init how to contact remote agent
  mbus: https://admin:admin@vps-server.softlayer.com:6868   <Please be consistent with the VmNamePrefix in hostname>

  properties:
    softlayer: *softlayer

    # Tells CPI how agent should listen for bosh-init requests
    agent: {mbus: "https://admin:admin@vps-server.softlayer.com:6868"}   <Please be consistent with the VmNamePrefix in hostname>

    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}

    ntp: *ntp